# Site settings
title: BrunoSolutions
email: MarkBruns@MarkBruns.com
description: SERVE your core constituencies FIRST! Enlist these people in becoming their own solution, dogfooding their own toolset.
twitter_username: MarkBruns
github_username:  BRUNOSolutions

# Build settings
markdown: kramdown
