# Site settings
title: Bruno Solutions
email: MarkBruns@MarkBruns.com
description: Don't Believe Me. Just Watch. Your Mind Will Be Programmed, So Control The Projector.
twitter_username: MarkBruns
github_username:  MarkBruns

# Build settings
markdown: kramdown
