# Site settings
title: Bruno Solutions
email: MarkBruns@MarkBruns.com
description: Don't Believe Me. Just Watch. Be Aware Of The Programming of Your Mind. Control Your Own Projector.
twitter_username: MarkBruns
github_username:  MarkBruns

# Build settings
markdown: kramdown
