# Site settings
title: BrunoSolutions
email: MarkBruns@MarkBruns.com
description: SERVE your core constituencies FIRST!  SERVING FIRST means enlisting these people in the task of becoming their own solution, dogfooding their own toolset.
twitter_username: MarkBruns
github_username:  BRUNOSolutions

# Build settings
markdown: kramdown
