# Site settings
title: BrunoSolutions
email: MarkBruns@MarkBruns.com
description: DOGE-fooding Leadership. SERVE FIRST!  
twitter_username: MarkBruns
github_username:  BRUNOSolutions

# Build settings
markdown: kramdown
