# Site settings
title: BrunoSolutions
email: MarkBruns@MarkBruns.com
description: 2024 is for STUDYING How to Best Run for POTUS in 2028
twitter_username: MarkBruns
github_username:  BRUNOSolutions

# Build settings
markdown: kramdown
