# Site settings
title: BrunoSolutions
email: MarkBruns@MarkBruns.com
description: The solutions are complex and DIFFERENT, but they are mostly about hybrid cognitive intelligence and discipline.
twitter_username: MarkBruns
github_username:  BRUNOSolutions

# Build settings
markdown: kramdown
