# Site settings
title: BrunoSolutions
email: MarkBruns@MarkBruns.com
description: The solutions are complex and cognitively DIFFERENT, but mostly about hybrid intelligence and recursively-intentioned improvement of discipline.
twitter_username: MarkBruns
github_username:  BRUNOSolutions

# Build settings
markdown: kramdown
