# Site settings
title: Bruno Solutions
email: MarkBruns@MarkBruns.com
description: Discipline Equals Freedom
twitter_username: MarkBruns
github_username:  MarkBruns

# Build settings
markdown: kramdown
